name: quran_cloud
description: "A Flutter package for integrating with Al-Quran Cloud API to provide Quran data, recitations, and translations."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client
  dio: ^5.3.3
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Utilities
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  
  # JSON serialization code generation
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
